/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando TeTz
 */
public abstract class ModeloAdicionar extends javax.swing.JDialog implements ActionListener {

    /**
     * Creates new form ModeloAdicionar
     */
    public ModeloAdicionar() {
        try {
            initComponents();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(), "Tela de erro",
                    JOptionPane.ERROR_MESSAGE);
        }
        ImageIcon icone = new ImageIcon("src/Imagens/icone.png");
        setIconImage(icone.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelS1 = new javax.swing.JPanel();
        bSalvar = new javax.swing.JButton();
        bLimpar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        bSalvar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bSalvar.setForeground(new java.awt.Color(51, 102, 255));
        bSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/floppy-icon.png"))); // NOI18N
        bSalvar.setText("Salvar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        bLimpar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bLimpar.setForeground(new java.awt.Color(51, 102, 255));
        bLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Clear-icon.png"))); // NOI18N
        bLimpar.setText("Limpar");
        bLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparActionPerformed(evt);
            }
        });

        bCancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bCancelar.setForeground(new java.awt.Color(51, 102, 255));
        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        bCancelar.setText("Sair");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("* Campos obrigatórios");

        javax.swing.GroupLayout painelS1Layout = new javax.swing.GroupLayout(painelS1);
        painelS1.setLayout(painelS1Layout);
        painelS1Layout.setHorizontalGroup(
            painelS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelS1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(bSalvar)
                .addGap(18, 18, 18)
                .addComponent(bLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(bCancelar)
                .addContainerGap())
        );
        painelS1Layout.setVerticalGroup(
            painelS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelS1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalvar)
                    .addComponent(bLimpar))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(painelS1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelS1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCancelar)
                .addContainerGap())
        );

        getContentPane().add(painelS1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent evt) {
        if (evt.getSource() == bSalvar) {
            this.bSalvarActionPerformed(evt);
        } else if (evt.getSource() == bLimpar) {
            this.bLimparActionPerformed(evt);
        } else if (evt.getSource() == bCancelar) {
            this.bCancelarActionPerformed(evt);
        }
    }

    public abstract void bSalvarActionListener(ActionEvent evt);

    public abstract void bLimparActionListener(ActionEvent evt);

    public abstract void bCancelarActionListener(ActionEvent evt);
    
    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        bSalvarActionListener(evt);
    }//GEN-LAST:event_bSalvarActionPerformed

    private void bLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparActionPerformed
        bLimparActionListener(evt);
    }//GEN-LAST:event_bLimparActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        bCancelarActionListener(evt);
    }//GEN-LAST:event_bCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton bCancelar;
    protected javax.swing.JButton bLimpar;
    protected javax.swing.JButton bSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel painelS1;
    // End of variables declaration//GEN-END:variables
}
