/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import TipoDados.TxtComUndoRedo;

/**
 *
 * @author Fernando TeTz
 */
public abstract class ModeloManutenção extends javax.swing.JInternalFrame implements ActionListener {

    /**
     * Creates new form ModeloAdicionar
     */
    public ModeloManutenção() {
        try {
            initComponents();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(), "Tela de erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelN1 = new javax.swing.JPanel();
        cbPesquisa = new javax.swing.JComboBox<>();
        tPesquisa = new TxtComUndoRedo();
        labelPesquisar1 = new javax.swing.JLabel();
        bMostrarTodos = new javax.swing.JButton();
        bLimparTudo = new javax.swing.JButton();
        cbDiaPesquisa = new javax.swing.JComboBox<>();
        cbMesPesquisa = new javax.swing.JComboBox<>();
        cbAnoPesquisa = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        painelS1 = new javax.swing.JPanel();
        bNovo = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bSair = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone.png"))); // NOI18N

        cbPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPesquisa.setMaximumSize(new java.awt.Dimension(56, 20));
        cbPesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPesquisaItemStateChanged(evt);
            }
        });

        tPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tPesquisaKeyReleased(evt);
            }
        });

        labelPesquisar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lupa.png"))); // NOI18N
        labelPesquisar1.setText("PESQUISAR:");

        bMostrarTodos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bMostrarTodos.setForeground(new java.awt.Color(51, 102, 255));
        bMostrarTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/tudo.png"))); // NOI18N
        bMostrarTodos.setText("Mostrar todos");
        bMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMostrarTodosActionPerformed(evt);
            }
        });

        bLimparTudo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bLimparTudo.setForeground(new java.awt.Color(51, 102, 255));
        bLimparTudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Clear-icon.png"))); // NOI18N
        bLimparTudo.setText("Limpar");
        bLimparTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparTudoActionPerformed(evt);
            }
        });

        cbDiaPesquisa.setMaximumRowCount(10000);
        cbDiaPesquisa.setEnabled(false);
        cbDiaPesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDiaPesquisaItemStateChanged(evt);
            }
        });

        cbMesPesquisa.setMaximumRowCount(10000);
        cbMesPesquisa.setEnabled(false);
        cbMesPesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMesPesquisaItemStateChanged(evt);
            }
        });

        cbAnoPesquisa.setMaximumRowCount(10000);
        cbAnoPesquisa.setEnabled(false);
        cbAnoPesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAnoPesquisaItemStateChanged(evt);
            }
        });

        jLabel8.setText("/");

        jLabel6.setText("/");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/data.png"))); // NOI18N

        javax.swing.GroupLayout painelN1Layout = new javax.swing.GroupLayout(painelN1);
        painelN1.setLayout(painelN1Layout);
        painelN1Layout.setHorizontalGroup(
            painelN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelN1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbDiaPesquisa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMesPesquisa, 0, 108, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAnoPesquisa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(192, 192, 192))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelN1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(bMostrarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bLimparTudo, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addGap(144, 144, 144))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelN1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelPesquisar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelN1Layout.setVerticalGroup(
            painelN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelN1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPesquisar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbDiaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(cbMesPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(cbAnoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addGroup(painelN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bMostrarTodos)
                    .addComponent(bLimparTudo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(painelN1, java.awt.BorderLayout.PAGE_START);

        bNovo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bNovo.setForeground(new java.awt.Color(51, 102, 255));
        bNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        bNovo.setText("Novo");
        bNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoActionPerformed(evt);
            }
        });

        bEditar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bEditar.setForeground(new java.awt.Color(51, 102, 255));
        bEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        bSair.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bSair.setForeground(new java.awt.Color(51, 102, 255));
        bSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        bSair.setText("Sair");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });

        bExcluir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bExcluir.setForeground(new java.awt.Color(51, 102, 255));
        bExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/deletar.png"))); // NOI18N
        bExcluir.setText("Excluir");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelS1Layout = new javax.swing.GroupLayout(painelS1);
        painelS1.setLayout(painelS1Layout);
        painelS1Layout.setHorizontalGroup(
            painelS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelS1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(bNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addComponent(bSair)
                .addContainerGap())
        );
        painelS1Layout.setVerticalGroup(
            painelS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelS1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNovo)
                    .addComponent(bEditar)
                    .addComponent(bSair)
                    .addComponent(bExcluir))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(painelS1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent evt) {
        if (evt.getSource() == bNovo) {
            this.bNovoActionPerformed(evt);
        } else if (evt.getSource() == bEditar) {
            this.bEditarActionPerformed(evt);
        } else if (evt.getSource() == bSair) {
            this.bSairActionPerformed(evt);
        } else if (evt.getSource() == bMostrarTodos) {
            this.bMostrarTodosActionPerformed(evt);
        } else if (evt.getSource() == bLimparTudo) {
            this.bLimparTudoActionPerformed(evt);
        }else if (evt.getSource() == bExcluir) {
            this.bExcluirActionPerformed(evt);
        }
    }

    public abstract void bNovoActionListener(ActionEvent evt);

    public abstract void bEditarActionListener(ActionEvent evt);

    public abstract void bSairActionListener(ActionEvent evt);

    public abstract void bExcluirActionListener(ActionEvent evt);
    
    public abstract void bMostrarTodosActionListener(ActionEvent evt);

    public abstract void bLimparTudoActionListener(ActionEvent evt);
    
    public abstract void txPesquisa();
    
    public abstract void mudouCB();

    private void bNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoActionPerformed
        bNovoActionListener(evt);
    }//GEN-LAST:event_bNovoActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        bEditarActionListener(evt);
    }//GEN-LAST:event_bEditarActionPerformed

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        bSairActionListener(evt);
    }//GEN-LAST:event_bSairActionPerformed

    private void tPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPesquisaKeyReleased
        txPesquisa();
    }//GEN-LAST:event_tPesquisaKeyReleased

    private void bMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMostrarTodosActionPerformed
        bMostrarTodosActionListener(evt);
    }//GEN-LAST:event_bMostrarTodosActionPerformed

    private void bLimparTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparTudoActionPerformed
        bLimparTudoActionListener(evt);
    }//GEN-LAST:event_bLimparTudoActionPerformed

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
        bExcluirActionListener(evt);
    }//GEN-LAST:event_bExcluirActionPerformed

    private void cbPesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPesquisaItemStateChanged
        mudouCB();
    }//GEN-LAST:event_cbPesquisaItemStateChanged

    private void cbDiaPesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDiaPesquisaItemStateChanged
        txPesquisa();
    }//GEN-LAST:event_cbDiaPesquisaItemStateChanged

    private void cbMesPesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMesPesquisaItemStateChanged
        txPesquisa();
    }//GEN-LAST:event_cbMesPesquisaItemStateChanged

    private void cbAnoPesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAnoPesquisaItemStateChanged
        txPesquisa();
    }//GEN-LAST:event_cbAnoPesquisaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton bEditar;
    protected javax.swing.JButton bExcluir;
    protected javax.swing.JButton bLimparTudo;
    protected javax.swing.JButton bMostrarTodos;
    protected javax.swing.JButton bNovo;
    protected javax.swing.JButton bSair;
    public javax.swing.JComboBox<String> cbAnoPesquisa;
    public javax.swing.JComboBox<String> cbDiaPesquisa;
    public javax.swing.JComboBox<String> cbMesPesquisa;
    protected javax.swing.JComboBox<String> cbPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel labelPesquisar1;
    private javax.swing.JPanel painelN1;
    private javax.swing.JPanel painelS1;
    protected javax.swing.JTextField tPesquisa;
    // End of variables declaration//GEN-END:variables
}
