/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando TeTz
 */
public class TelaInicial extends javax.swing.JFrame {

    public static int max = 0;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        setLocation(250, 0);
        setSize(900, 700);
        ImageIcon icone = new ImageIcon("src/Imagens/icone.png");
        setIconImage(icone.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuEfetuarEmprestimo = new javax.swing.JMenuItem();
        menuEfetuarDevolucao = new javax.swing.JMenuItem();
        menuPagarMulta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuAdicionarLivro = new javax.swing.JMenuItem();
        menuRevistas = new javax.swing.JMenuItem();
        menuAutores = new javax.swing.JMenuItem();
        menuEditoras = new javax.swing.JMenuItem();
        menuAssociados = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuAtt = new javax.swing.JMenuItem();
        menuContato = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIBLIOTECA v1.3");
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        Desktop.setBackground(new java.awt.Color(0, 153, 204));
        Desktop.setMaximumSize(new java.awt.Dimension(900, 600));
        Desktop.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/wallpaperStart.jpg"))); // NOI18N

        Desktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesktopLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jMenu1.setText("Empréstimo");

        menuEfetuarEmprestimo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        menuEfetuarEmprestimo.setText("Efetuar empréstimo");
        menuEfetuarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEfetuarEmprestimoActionPerformed(evt);
            }
        });
        jMenu1.add(menuEfetuarEmprestimo);

        menuEfetuarDevolucao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        menuEfetuarDevolucao.setText("Efetuar devolução");
        menuEfetuarDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEfetuarDevolucaoActionPerformed(evt);
            }
        });
        jMenu1.add(menuEfetuarDevolucao);

        menuPagarMulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        menuPagarMulta.setText("Pagar multa");
        menuPagarMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPagarMultaActionPerformed(evt);
            }
        });
        jMenu1.add(menuPagarMulta);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Manutenção");

        menuAdicionarLivro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        menuAdicionarLivro.setText("Livros");
        menuAdicionarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdicionarLivroActionPerformed(evt);
            }
        });
        jMenu3.add(menuAdicionarLivro);

        menuRevistas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        menuRevistas.setText("Revistas");
        menuRevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRevistasActionPerformed(evt);
            }
        });
        jMenu3.add(menuRevistas);

        menuAutores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        menuAutores.setText("Autores");
        menuAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAutoresActionPerformed(evt);
            }
        });
        jMenu3.add(menuAutores);

        menuEditoras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        menuEditoras.setText("Editoras");
        menuEditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditorasActionPerformed(evt);
            }
        });
        jMenu3.add(menuEditoras);

        menuAssociados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menuAssociados.setText("Associados");
        menuAssociados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAssociadosActionPerformed(evt);
            }
        });
        jMenu3.add(menuAssociados);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");

        menuAtt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        menuAtt.setText("Buscar atualizações");
        menuAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAttActionPerformed(evt);
            }
        });
        jMenu4.add(menuAtt);

        menuContato.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuContato.setText("Contato");
        menuContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContatoActionPerformed(evt);
            }
        });
        jMenu4.add(menuContato);

        menuSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        jMenu4.add(menuSobre);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAdicionarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdicionarLivroActionPerformed
        if (max == 0) {
            max++;
            TelaManutençãoLivro tela = null;
            try {
                tela = new TelaManutençãoLivro();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir manutenção de livros");
            }
            Desktop.add(tela);
            tela.setVisible(true);
            tela.setLocation(30, 30);
            tela.setSize(750, 500);
        } else {
            JOptionPane.showMessageDialog(null, "Saia das outras operações para poder começar outra!",
                    "SOMENTE UMA OPERAÇÃO POR VEZ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_menuAdicionarLivroActionPerformed

    private void menuAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAutoresActionPerformed
        if (max == 0) {
            max++;
            TelaManutençãoAutor tela = null;
            try {
                tela = new TelaManutençãoAutor();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir manutenção de autores");
            }
            Desktop.add(tela);
            tela.setVisible(true);
            tela.setLocation(150, 30);

        } else {
            JOptionPane.showMessageDialog(null, "Saia das outras operações para poder começar outra!",
                    "SOMENTE UMA OPERAÇÃO POR VEZ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_menuAutoresActionPerformed

    private void menuEditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditorasActionPerformed
        if (max == 0) {
            max++;
            TelaManutençãoEditora tela = null;
            try {
                tela = new TelaManutençãoEditora();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir manutenção de editoras");
            }
            Desktop.add(tela);
            tela.setVisible(true);
            tela.setLocation(150, 30);
        } else {
            JOptionPane.showMessageDialog(null, "Saia das outras operações para poder começar outra!",
                    "SOMENTE UMA OPERAÇÃO POR VEZ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_menuEditorasActionPerformed

    private void menuAssociadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAssociadosActionPerformed
        if (max == 0) {
            max++;
            TelaManutençãoAssociado tela = null;
            try {
                tela = new TelaManutençãoAssociado();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir manutenção de associado");
            }
            Desktop.add(tela);
            tela.setVisible(true);
            tela.setLocation(30, 30);
            tela.setSize(750, 500);

        } else {
            JOptionPane.showMessageDialog(null, "Saia das outras operações para poder começar outra!",
                    "SOMENTE UMA OPERAÇÃO POR VEZ", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_menuAssociadosActionPerformed

    private void menuRevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRevistasActionPerformed
        if (max == 0) {
            max++;
            TelaManutençãoRevista tela = null;
            try {
                tela = new TelaManutençãoRevista();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir manutenção de revistas");
            }
            Desktop.add(tela);
            tela.setVisible(true);
            tela.setLocation(110, 30);
            tela.setSize(650, 500);
        } else {
            JOptionPane.showMessageDialog(null, "Saia das outras operações para poder começar outra!",
                    "SOMENTE UMA OPERAÇÃO POR VEZ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_menuRevistasActionPerformed

    private void menuEfetuarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEfetuarEmprestimoActionPerformed
        if (max == 0) {
            max++;
            TelaEfetuarEmprestimo tela = null;
            try {
                tela = new TelaEfetuarEmprestimo();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir efetuar emprestimo");
            }
            Desktop.add(tela);
            tela.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Saia das outras operações para poder começar outra!",
                    "SOMENTE UMA OPERAÇÃO POR VEZ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_menuEfetuarEmprestimoActionPerformed

    private void menuEfetuarDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEfetuarDevolucaoActionPerformed
        if (max == 0) {
            max++;
            TelaEfetuarDevolucao tela = null;
            try {
                tela = new TelaEfetuarDevolucao();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir efetuar devolucao");
            }
            Desktop.add(tela);
            tela.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Saia das outras operações para poder começar outra!",
                    "SOMENTE UMA OPERAÇÃO POR VEZ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_menuEfetuarDevolucaoActionPerformed

    private void menuPagarMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPagarMultaActionPerformed
        if (max == 0) {
            max++;
            TelaPagarMultas tela = null;
            try {
                tela = new TelaPagarMultas();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir pagar multas");
            }
            Desktop.add(tela);
            tela.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Saia das outras operações para poder começar outra!",
                    "SOMENTE UMA OPERAÇÃO POR VEZ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_menuPagarMultaActionPerformed

    private void menuContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContatoActionPerformed
        if (max == 0) {
            max++;
            TelaContato tela = null;
            try {
                tela = new TelaContato();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir contato");
            }
            tela.setLocationRelativeTo(this);
            tela.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Saia das outras operações para poder começar outra!",
                    "SOMENTE UMA OPERAÇÃO POR VEZ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_menuContatoActionPerformed

    private void menuAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAttActionPerformed
        JOptionPane.showMessageDialog(null,"Não existe atualizações disponíveis no momento.","ATUALIZAÇÃO INDISPONIVEL",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuAttActionPerformed

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        if (max == 0) {
            max++;
            TelaSobre tela = null;
            try {
                tela = new TelaSobre();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir contato");
            }
            tela.setLocationRelativeTo(this);
            tela.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Saia das outras operações para poder começar outra!",
                    "SOMENTE UMA OPERAÇÃO POR VEZ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_menuSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaInicial().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane Desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAdicionarLivro;
    private javax.swing.JMenuItem menuAssociados;
    private javax.swing.JMenuItem menuAtt;
    private javax.swing.JMenuItem menuAutores;
    private javax.swing.JMenuItem menuContato;
    private javax.swing.JMenuItem menuEditoras;
    private javax.swing.JMenuItem menuEfetuarDevolucao;
    private javax.swing.JMenuItem menuEfetuarEmprestimo;
    private javax.swing.JMenuItem menuPagarMulta;
    private javax.swing.JMenuItem menuRevistas;
    private javax.swing.JMenuItem menuSobre;
    // End of variables declaration//GEN-END:variables
}
