/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import TipoDados.Associado;
import TipoDados.Multa;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * a
 *
 * @author Fernando TeTz
 */
public class TelaPagarMultas extends ModeloEmprestimos {

    ArrayList<Associado> associados = new ArrayList<>();
    ArrayList<Multa> multas = new ArrayList<>();
    Associado associado = new Associado();
    public static double valorPagoMulta;
    int verificador = -1;
    BigDecimal bd;

    public TelaPagarMultas() throws Exception {
        try {
            lerArquivoAssociados();
        } catch (Exception ee) {
            JOptionPane.showMessageDialog(null, "Arquivo 'ArqAssociados.dad' não encontrado.\nVá à manutenção de associados"
                    + "para resolução do problema.", "Tela de erro", JOptionPane.ERROR_MESSAGE);
        }
        try {
            lerArquivoMultas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Arquivo 'ArqMultas.dad' não encontrado. Um novo arquivo será criado.",
                    "Tela de erro", JOptionPane.ERROR_MESSAGE);
            gravaArquivoMultas();
        }
        initComponents();
        bSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pagarMulta.png")));
        bSalvar.setText("Pagar multa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tCPF = new javax.swing.JFormattedTextField();
        labelCPF = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tNome = new javax.swing.JTextField();
        tTelefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        labelDia = new javax.swing.JLabel();
        tValorMultaPendente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tValorSerPago = new javax.swing.JLabel();
        bInserirValorPago = new javax.swing.JButton();

        setTitle("Pagamento de multa");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone.png"))); // NOI18N

        jPanel1.setToolTipText("");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do associado"));
        jPanel2.setToolTipText("");

        try {
            tCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tCPF.setToolTipText("Digite o CPF do associado");
        tCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tCPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tCPFFocusLost(evt);
            }
        });

        labelCPF.setText("* CPF:");

        jLabel1.setText("Nome:");

        jLabel2.setText("Telefone:");

        tNome.setToolTipText("Nome do associado");
        tNome.setEnabled(false);

        tTelefone.setToolTipText("Telefone do associado");
        tTelefone.setEnabled(false);

        jLabel3.setText("Valor de multa pendente:");
        jLabel3.setToolTipText("Data do empréstimo");

        labelDia.setText("R$");
        labelDia.setToolTipText("Data do empréstimo");

        tValorMultaPendente.setText("0.0");

        jLabel4.setText("Valor a ser pago: R$");

        tValorSerPago.setText("0.0");

        bInserirValorPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cash_B-512.png"))); // NOI18N
        bInserirValorPago.setText("Inserir valor a ser pago");
        bInserirValorPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInserirValorPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tValorSerPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tValorMultaPendente, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(bInserirValorPago))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCPF)
                    .addComponent(tCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tValorMultaPendente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(labelDia)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tValorSerPago, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bInserirValorPago)))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCPFFocusGained
        labelCPF.setForeground(Color.BLACK);
    }//GEN-LAST:event_tCPFFocusGained

    private void tCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCPFFocusLost
        try {
            lerArquivoAssociados();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir arquivo de associados. Verifique se existe cadastros de associados.",
                    "Tela de erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            lerArquivoMultas();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir arquivo de multas.",
                    "Tela de erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        for (int x = 0; x < associados.size(); x++) { //PERCORRE TODOS ASSOCIADOS
            if (associados.get(x).getCpfAssociado().equals(tCPF.getText())) {
                associado.setCpfAssociado(tCPF.getText());
                associado.setEmail(associados.get(x).getEmail());
                associado.setEndereco(associados.get(x).getEndereco());
                associado.setNome(associados.get(x).getNome());
                associado.setTelefone(associados.get(x).getTelefone());
                tNome.setText(associado.getNome());
                tTelefone.setText(associado.getTelefone());
                verificador = 0;
                break;
            }
        }
        for (int i = 0; i < multas.size(); i++) {
            if (multas.get(i).getAssociado().getCpfAssociado().equals(associado.getCpfAssociado())) {
                tValorMultaPendente.setText(Double.toString(multas.get(i).getValorMulta()));
                verificador = 0;
                break;
            } else {
                verificador = 1;
            }
        }
        if (verificador == -1) {
            JOptionPane.showMessageDialog(null, "Não foi encontrado o associado com CPF " + tCPF.getText() + ".\nDigite outro CPF.");
            labelCPF.setForeground(Color.red);
        } else if (verificador == 1) {
            JOptionPane.showMessageDialog(null, "Não foi encontrado multas "
                    + "pendentes relacionadas ao associado com CPF " + tCPF.getText() + ".\nDigite outro CPF.");
            labelCPF.setForeground(Color.red);
        }
    }//GEN-LAST:event_tCPFFocusLost

    private void bInserirValorPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInserirValorPagoActionPerformed
        bInserirValorPago.setForeground(Color.black);
        TelaInserirValorPagamento telaInsert = new TelaInserirValorPagamento();
        telaInsert.setVisible(true);
    }//GEN-LAST:event_bInserirValorPagoActionPerformed

    private void lerArquivoAssociados() throws Exception {
        ObjectInputStream arquivo = null;
        Associado associadox = null;
        associados.clear();
        try {
            arquivo = new ObjectInputStream(new FileInputStream("ArqAssociados.dad"));
            do {
                associadox = (Associado) arquivo.readObject();
                associados.add(associadox);
            } while (associadox != null);
        } catch (EOFException e) {
            arquivo.close();
        }
    }

    private void lerArquivoMultas() throws Exception {
        ObjectInputStream arquivo = null;
        Multa multax = null;
        multas.clear();
        try {
            arquivo = new ObjectInputStream(new FileInputStream("ArqMultas.dad"));
            do {
                multax = (Multa) arquivo.readObject();
                multas.add(multax);
            } while (multax != null);
        } catch (EOFException e) {
            arquivo.close();
        }
    }

    @Override
    public void bSalvarActionListener(ActionEvent evt) {
        int result;
        if (tValorSerPago.getText().equals("0.0")) {
            JOptionPane.showMessageDialog(null, "Insira um valor a ser pago!", "NENHUM VALOR INSERIDO", JOptionPane.ERROR_MESSAGE);
            bInserirValorPago.setForeground(Color.RED);
            return;
        }
        if (verificador == -1) {
            JOptionPane.showMessageDialog(null, "Digite o CPF de um associado!", "NENHUM ASSOCIADO INSERIDO", JOptionPane.ERROR_MESSAGE);
            labelCPF.setForeground(Color.red);
            return;
        }
        if (verificador == 1) {
            JOptionPane.showMessageDialog(null, "Não foi encontrado multas "
                    + "pendentes relacionadas ao associado com CPF " + tCPF.getText() + ".\nDigite outro CPF.");
            labelCPF.setForeground(Color.red);
            return;
        }
        try {
            lerArquivoAssociados();
        } catch (Exception ex) {
        }
        try {
            lerArquivoMultas();
        } catch (Exception ex) {
        }
        bd = new BigDecimal(valorPagoMulta).setScale(2, RoundingMode.HALF_EVEN);
        result = JOptionPane.showConfirmDialog(null, "Efetuar um pagamento de valor: R$'"
                + bd.doubleValue() + " que será descontado da multa do associado '" + associado.getNome() + " ?");
        if (result == 0) { //Resposta SIM
            int idt = 0;
            for (int i = 0; i < multas.size(); i++) { //PERCORRE TODAS AS MULTAS
                if (multas.get(i).getAssociado().getCpfAssociado().equals(associado.getCpfAssociado())) {
                    double resto = multas.get(i).getValorMulta() - valorPagoMulta;
                    if (resto < 0) {
                        JOptionPane.showMessageDialog(null, "O valor inserido é maior que o valor da multa pendente."
                                + " Não se pode ficar com créditos na conta!", "VALOR PAGO MAIOR QUE DA MULTA",
                                JOptionPane.ERROR_MESSAGE);
                        return;
                    } else {
                        multas.get(i).setValorMulta(resto);
                        JOptionPane.showMessageDialog(null, "Valor descontado da multa pendente do associado '"
                                + associado.getNome() + "'. Restou R$" + resto + " de multa.");
                        break;
                    }
                }
            }
            JOptionPane.showMessageDialog(null, "Pagamento de multa realizada com sucesso.",
                    "PAGAMENTO DE MULTA CONCLUÍDA", JOptionPane.INFORMATION_MESSAGE);
            try {
                gravaArquivoMultas();
            } catch (Exception ex) {
                System.out.print(ex);
            }
            LimpaCampos();
            result = JOptionPane.showConfirmDialog(null, "Deseja efetuar outro pagamento de multa?",
                    "OUTRO PAGAMENTO", JOptionPane.YES_NO_OPTION);
            if (result == 1) { //RESPOSTA NÃO
                bSalvar.setText("Salvar");
                bSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/floppy-icon.png")));
                TelaInicial.max = 0;
                this.dispose();
            }
        }

    }

    @Override
    public void bLimparActionListener(ActionEvent evt) {
        int result = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja limpar tudo?");
        if (result == 0) { //Resposta SIM
            LimpaCampos();
        }
    }

    @Override
    public void bSairActionListener(ActionEvent evt) {
        int result = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair da operação?",
                "SAIR", JOptionPane.YES_NO_OPTION);
        if (result == 0) {
            bSalvar.setText("Salvar");
            bSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/floppy-icon.png")));
            TelaInicial.max = 0;
            this.dispose();
        }
    }

    private void gravaArquivoMultas() throws Exception {
        try {
            ObjectOutputStream arquivo = new ObjectOutputStream(new FileOutputStream("ArqMultas.dad"));
            for (Multa multax : multas) {
                arquivo.writeObject(multax);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Erro ao gravar arquivo.", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void LimpaCampos() {
        tCPF.setText("");
        tNome.setText("");
        tTelefone.setText("");
        tValorMultaPendente.setText("0.0");
        tValorSerPago.setText("0.0");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bInserirValorPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelDia;
    private javax.swing.JFormattedTextField tCPF;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tTelefone;
    private javax.swing.JLabel tValorMultaPendente;
    public static javax.swing.JLabel tValorSerPago;
    // End of variables declaration//GEN-END:variables

}
