/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import TipoDados.Editora;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import TipoDados.TxtComUndoRedo;

/**
 *
 * @author Fernando TeTz
 */
public class TelaAdicionarEditora extends ModeloAdicionar {

    ArrayList<Editora> editoras = new ArrayList<>();
    Editora editora = null;

    public TelaAdicionarEditora() {
        try {
            lerArquivo();
        } catch (Exception ex) {
        }
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelRazao = new javax.swing.JLabel();
        tRazaoSocial = new TxtComUndoRedo();

        setTitle("Adicionar Editora");

        labelRazao.setText("* Razão Social:");

        tRazaoSocial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tRazaoSocialFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRazao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRazao)
                    .addComponent(tRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tRazaoSocialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tRazaoSocialFocusGained
        labelRazao.setForeground(Color.black);
    }//GEN-LAST:event_tRazaoSocialFocusGained

    private void lerArquivo() throws Exception {
        ObjectInputStream arquivo = null;
        Editora editorax = null;
        editoras.clear();
        try {
            arquivo = new ObjectInputStream(new FileInputStream("ArqEditoras.dad"));
            do {
                editorax = (Editora) arquivo.readObject();
                editoras.add(editorax);
            } while (editorax != null);
        } catch (EOFException e) {
            arquivo.close();
        }
    }

    @Override
    public void bSalvarActionListener(ActionEvent evt) {
        try {
            int result = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja adicionar a nova editora?");
            int tam;
            Editora newEditora = new Editora();
            if (result == 0) { //Resposta SIM
                if (tRazaoSocial.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!",
                            "CAMPOS OBRIGATÓRIOS!", JOptionPane.ERROR_MESSAGE);
                    labelRazao.setForeground(Color.RED);
                    return;
                }
                for (Editora edit : editoras) {
                    if (edit.getRazaoSocial().equals(tRazaoSocial.getText())) {
                        JOptionPane.showMessageDialog(null, "Já existe uma editora com"
                                + "a Razão Social '" + edit.getRazaoSocial() + "'. Digite outra.",
                                "EDITORA JÁ CADASTRADA!", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                } //NÃO EXISTE RAZÃO SOCIAL CADASTRADA
                tam = editoras.size();
                newEditora.setRazaoSocial(tRazaoSocial.getText());
                if (tam == 0) {
                    newEditora.setIdEditora(0);
                } else {
                    newEditora.setIdEditora(editoras.get(tam - 1).getIdEditora() + 1);
                }
                editoras.add(newEditora);
                gravaArquivo();
                tRazaoSocial.setText("");
                JOptionPane.showMessageDialog(null, "Editora cadastrada com sucesso.", "CADASTRO DE EDITORA",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao gravar em ArqEditoras.biblio\n" + ex.getMessage(),
                    "Tela de erro", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }

    @Override
    public void bLimparActionListener(ActionEvent evt) {
        int result = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja limpar tudo?");
        if (result == 0) { //Resposta SIM
            tRazaoSocial.setText("");
        }
    }

    @Override
    public void bCancelarActionListener(ActionEvent evt) {
        int result;
        try {
            result = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair da operação?",
                    "CANCELAR", JOptionPane.YES_NO_OPTION);
            if (result == 0) {
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Tela de erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void gravaArquivo() throws Exception {
        try {
            ObjectOutputStream arquivo = new ObjectOutputStream(new FileOutputStream("ArqEditoras.dad"));
            for (Editora editora1 : editoras) {
                arquivo.writeObject(editora1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gravar arquivo.", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelRazao;
    private javax.swing.JTextField tRazaoSocial;
    // End of variables declaration//GEN-END:variables

}
