/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import TipoDados.Autor;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import TipoDados.TxtComUndoRedo;
/**
 *
 * @author Fernando TeTz
 */
public class TelaAdicionarAutor extends ModeloAdicionar {

    ArrayList<Autor> autores = new ArrayList<>();
    Autor autor = null;

    public TelaAdicionarAutor() {
        try {
            lerArquivo();
        } catch (Exception ex) {
        }
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        tNome = new TxtComUndoRedo();

        setTitle("Adicionar Autor");

        labelNome.setText("* Nome:");

        tNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tNomeFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNomeFocusGained
        labelNome.setForeground(Color.black);
    }//GEN-LAST:event_tNomeFocusGained

    private void lerArquivo() throws Exception {
        ObjectInputStream arquivo = null;
        Autor autorx = null;
        autores.clear();
        try {
            arquivo = new ObjectInputStream(new FileInputStream("ArqAutores.dad"));
            do {
                autorx = (Autor) arquivo.readObject();
                autores.add(autorx);
            } while (autorx != null);
        } catch (EOFException e) {
            arquivo.close();
        }
    }

    @Override
    public void bSalvarActionListener(ActionEvent evt) {
        try {
            int result = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja adicionar o novo autor?");
            int tam;
            Autor newAutor = new Autor();
            if (result == 0) { //Resposta SIM
                if (tNome.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!",
                            "CAMPOS OBRIGATÓRIOS!", JOptionPane.ERROR_MESSAGE);
                    labelNome.setForeground(Color.RED);
                    return;
                }
                for (Autor edit : autores) {
                    if (edit.getNome().equals(tNome.getText())) {
                        JOptionPane.showMessageDialog(null, "Já existe um autor com"
                                + "o nome '" + edit.getNome() + "'. Digite outra.",
                                "AUTOR JÁ CADASTRADO!", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                } //NÃO EXISTE RAZÃO SOCIAL CADASTRADA
                tam = autores.size();
                newAutor.setNome(tNome.getText());
                if (tam == 0) {
                    newAutor.setIdAutor(0);
                } else {
                    newAutor.setIdAutor(autores.get(tam - 1).getIdAutor() + 1);
                }
                autores.add(newAutor);
                gravaArquivo();
                tNome.setText("");
                JOptionPane.showMessageDialog(null, "Autor cadastrado com sucesso.", "CADASTRO DE AUTOR",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao gravar em ArqAutor.biblio\n" + ex.getMessage(),
                    "Tela de erro", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }

    @Override
    public void bLimparActionListener(ActionEvent evt) {
        int result = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja limpar tudo?");
        if (result == 0) { //Resposta SIM
            tNome.setText("");
        }
    }

    @Override
    public void bCancelarActionListener(ActionEvent evt) {
        int result;
        try {
            result = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair da operação?",
                    "CANCELAR", JOptionPane.YES_NO_OPTION);
            if (result == 0) {
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Tela de erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void gravaArquivo() throws Exception {
        try {
            ObjectOutputStream arquivo = new ObjectOutputStream(new FileOutputStream("ArqAutores.dad"));
            for (Autor editora1 : autores) {
                arquivo.writeObject(editora1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gravar arquivo.", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JTextField tNome;
    // End of variables declaration//GEN-END:variables

}
